# see other Skiff packages for more advanced defaults:
#  - core/alpine
#  - core/ubuntu
#  - core/nixos
#  - core/gentoo
# Documented at https://github.com/skiffos/skiff-core
containers: # can add unlimited containers
  skiff_core: # name of the docker container
    image: skiffos/skiff-core-ubuntu:latest
    entrypoint: ["/lib/systemd/systemd"]
    stopSignal: RTMIN+3
    tty: false # causes setctty error
    disableInit: true
    workingDirectory: /
    mounts:
    - /dev:/dev
    - /lib/modules:/lib/modules
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /mnt:/mnt
    - /run/udev:/run/udev
    - /etc/resolv.conf:/etc/resolv.conf:ro
    privileged: true
    startAfterCreate: true
    restartPolicy: "always"
    capAdd:
    - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
    - seccomp=unconfined
    tmpFs:
      /run: rw,noexec,nosuid,size=65536k
      /run/lock: rw,noexec,nosuid,size=65536k
users: # can add unlimited users 
  core:
    container: skiff_core
    containerUser: core
    containerShell:
    - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-ubuntu:latest:
    pull:
      # images are provided for arm64, arm, amd64
      # also an option: policy: ifbuildfails
      policy: ifnotexists
      # avoid docker hub rate limits
      registry: quay.io
    build:
      source: /opt/skiff/coreenv/base
